browser-extensions/chrome/manifest.json
- For #9 
- Adds:
- www.parkrun.org.uk
- www.parkrun.com.au
- www.parkrun.co.nz
- www.parkrun.ca
- www.parkrun.ie
- www.parkrun.co.za
- www.parkrun.us
- www.parkrun.sg
=> Support other english language parkrun websites

browser-extensions/chrome/css/styles.css, browser-extensions/chrome/html/help.html, browser-extensions/chrome/html/options.html, browser-extensions/chrome/html/translations.html, browser-extensions/chrome/js/background.js, browser-extensions/chrome/js/content-scripts/content-script-athleteeventhistory.js, browser-extensions/chrome/js/content-scripts/content-script-athleteeventresultshistory.js, browser-extensions/chrome/js/content-scripts/content-script-athleteresultshistory.js, browser-extensions/chrome/js/lib/challenges.js, browser-extensions/chrome/js/lib/i18n.js, browser-extensions/chrome/js/translations.js, browser-extensions/chrome/manifest.json
- For #38 
- Supports including badges on Italian, Danish, Swedish, Finnish, French, German, Norweigan, and Russian websites
- Attempts to credit volunteering on all of the above too, but we are missing some translations of the roles, although some are in English so it was fine out of the box
- Abstracts the strings we look for in the page into an internationalisation (i18n) file and function so that we can add more languages easily. This is required when adding a new site.
- Also allows for translation of some of the link we add into the pages, but we don't have a good way of generating reasonable translations, so will probably asking for help of the community if they want it
=> Support other languages

browser-extensions/chrome/html/options.html, browser-extensions/chrome/js/background.js, browser-extensions/chrome/js/options.js, browser-extensions/chrome/manifest.json
- For #28 
- Fetch the Technical Event Information as well as the Geo XML (in parallel),
defaulting to previously fetched contents if we can't fetch the new info for some
reason when the cache has expired
- Update the manifest to allow fetching of data from wiki.parkrun.com
- Set the cache expiry to 3 days for the technical information to match that for 
the Geo XML
- Hide the debug information on the options page unless you give you athlete number as 'testing'
- Add 'Update Cache' button to the hidden options panel
- Add home parkrun information to the hidden options panel
- Rewrite most of the `options.js` page to cope with failures to fetch data
- Rewrite big chunks of `background.js` to handle incremental fetching of data
=> Skip future parkruns

browser-extensions/chrome/js/content-scripts/content-script-athleteeventhistory.js, browser-extensions/chrome/js/content-scripts/content-script-athleteeventresultshistory.js, browser-extensions/chrome/js/content-scripts/content-script-athleteresultshistory.js
- For #41 
- This now works for people who have done no parkruns, whereas
previous attempts to scan the page did not
- Fetches the athletedNumber directly from the URL path, not in the page
=> Switch to a better method of detmining athleteNumber

build/website/build.sh, website/_config.yml
- Add analytics ID to the main configuration
- Set the production build to use JEKYLL_ENV=production so that it is activated for this build
=> Add Google Analytics to production website

browser-extensions/common/js/lib/challenges.js
- uses `.getDate()` instead of `.getDay()`
- For #83
=> Fixes years-parkrunning is wrong if the month matches

.travis.yml
- Travis only makes secret variables available to PRs from the project's own repository, 
i.e. not forks, which means that the builds fail for any external PRs. This should skip the
staging website build for this type of contribution so that the build isn't marked as failed
=> Restrict building staging website to PRs from our own repo

browser-extensions/common/js/content-scripts/content-script-athleteeventresultshistory.js
I've been seeing some problems parsing the results table - at least on Chrome 70.0.3538.67.  Additional whitespace appearing in the innerText attribute prevents the extension from working correctly.  Adding trim() for each piece of data helps resolve the issue.
=> Trim whitespace during results table parse.

build/version.sh
- Make the git branch coexist with the need to put the version string in the `manifest.json`
=> Strip v from version string

browser-extensions/chrome/manifest.json
- None of the links were showing in Chrome because the browser polyfill
was missing and there was an error thrown when trying to get the icon.
=> Add browser polyfill to library path on Chrome for links

browser-extensions/common/js/lib/challenges.js, website/_data/stats.yml
- For #90
- Counts the longest run of different events visited before one is repeated.
- Some may argue that it isn't tourism if you include your nominal home parkrun
into account, but this does.
=> Add tourism streak stat

website/_posts/2019-05-19-alphabeteer-panic-what-happened-to-zary.markdown
- Reason for Polish name change apparently due to the spelling on the apricot tees
=> Add link to WithMeNow tweet

browser-extensions/common/js/lib/challenges.js, website/_data/stats.yml
Listening to the [parkrun adventurers](https://www.facebook.com/parkrunadventurers/) podcast [Episode 158](https://parkrunadventurers.podbean.com/e/episode-158-v-index/) where Mel introduced the concept of a "v-index": the number of volunteer roles you've performed at least _v_ times. I thought, "how hard can it be?"
A riff on the p-index code.
I'm not a Javascript programmer and this is my first attempt at coding for a browser extension so this might not be the best implementation.
I've tested this in Firefox and Chrome. [Mel has a v-index of 7](https://www.parkrun.com.au/results/athleteeventresultshistory/?athleteNumber=384152&eventNumber=0) (Run Director x 92, Timekeeper x 25, Photographer x 14, Barcode Scanning x 10, Tail Walker x 10, Other x 8, Volunteer Co-ordinator x 7) and [I have …
=> Introducing the v-index

browser-extensions/common/js/lib/challenges.js
- The Volunteer role list groups a few roles such as `Timekeeper`
and `Backup Timekeeper`, which wasn't reflected in the `v-index`
stat, so we can now do the same grouping for the stat as we do
for the list
- Fixes a bug in #169 we found during testing for [Athlete ID 1386351](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=1386351&eventNumber=0)
=> Group volunteer roles before stats and challenges

README.md, build/version.sh, website/_posts/2019-06-09-v0.7.6-released.markdown
- Add release blogpost
- Bump version number for the next development cycle
- Updates to the release doc
=> Post release tasks v0.7.6

.gitignore, README.md, build/website/build-local-and-run.sh
- Update build-local-and-run.sh script so that you can specify a custom Jekyll port when running the script  (eg if you already have a Jekyll container running on 4000).
- Update README with instructions on how to run the script instead of running the basic Docker run command which no longer works because common image directories (for extensions and website) are in root of the project.
- Added cache folder to gitignore - it was generated when running the script.
=> Updates to script to test website locally

Dockerfile, README.md
Updated Dockerfile to run npm command as root (otherwise it fails). As described in https://medium.com/@aguidrevitch/when-installation-of-global-package-using-npm-inside-docker-fails-b551b5dda389
Updated Docker run command in README to remove container on exit.
=> Fix Dockerfile to build extension

.gitignore, browser-extensions/chrome/manifest.json, browser-extensions/common/js/background.js, browser-extensions/common/js/content-scripts/content-script-athleteeventresultshistory.js, browser-extensions/common/js/lib/challenges.js, browser-extensions/common/js/lib/challenges_ui.js, browser-extensions/common/js/options.js, browser-extensions/firefox/manifest.json
- For #174 
- Attempts to get the basics working again with a switch from `geo.xml` to `events.json` as the data source.
- The Regionnaire challenge has been disabled (i.e. not possible to get the badge, 
and the table entry now just lists the numbers of events you have completed in each country.
The map stays, but it doesn't have any subregions anymore.
- Several extra checks have been added to try and not error when the event information is not available.
=> Switch from geo xml to events json

browser-extensions/common/js/background.js
I think this fixes #210 by removing an attempt to parse a cell in the technical wiki that's not present.  Could do with some further testing....as I can't currently explain why it's suddenly started causing a problem.
=> Remove attempt to parse cell that's not present

browser-extensions/common/js/lib/challenges.js
- Similar to #226 , use up less of the page for showing the same data, this 
time for obsessive badges.
- All the obsessive badges are now in a single challenge. You will
now get the highest available badge per year, rather than achieving
all of the ones you qualify for (i.e. if you get a gold badge one year,
you will no no-longer get the bronze and silver badges for that year
as well). After all, this is how it works in sport - the person
coming first doesn't get the medals for second and third too :)
- If you don't have any badges, or haven't yet achieved the highest
badge (gold) it will display placeholders to show what you could win
in the future for the ones you haven't surpassed yet.
=> Bundle the obsessive badges into a single table

browser-extensions/common/js/lib/challenges.js, website/_data/stats.yml
- Added row to the stats table ("Average parkrun event") to display the nearest parkrun event to the "Average parkrun lat/lon location" (already in stats table) #173 
- Made the name of the average parkrun event into a clickable link to take you to the homepage for that parkrun event.
- Made the "Furthest travelled" and "Nearest event not done yet (NENDY)" parkrun names into clickable links too so that it's consistent and not confusing to have some parkrun names clickable and some not.
- Added to release blog post.
=> Add nearest parkrun to average parkrun location stat

browser-extensions/common/js/lib/challenges.js
Fixes #235 
Tested against:
- Has only 5k parkruns: 1386351
- Has no 5k parkruns but has 2k parkruns: 5930968
- Has one 5k parkrun and some 2k parkruns: 2363530
- Has no parkruns at all: 1386351000
=> Add check so that no lat/lon means no nearest parkrun

browser-extensions/common/js/lib/challenges.js, browser-extensions/common/js/lib/challenges_ui.js
- The Voronoi map showed events that haven't started yet (such as the whole of the Netherlands)
- The parkrun Explorer table, also included these events, now it doesn't.
=> Voronoi map updates

.travis.yml, browser-extensions/common/README.md, browser-extensions/common/js/.gitignore, browser-extensions/common/js/lib/challenges.js, browser-extensions/common/js/package-lock.json, browser-extensions/common/js/package.json, browser-extensions/common/js/test/test_challenges.js
- If a parkrunner had only ever run at a single event, and this even was set as their home parkrun,
then an error would occur. This fixes it by computing the furthest event correctly.
- Example users hitting this problem as of 20200209:
- [Karen BRANGHAM](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=5725403&eventNumber=0) @ Chelmsford Central
- [Iain WILSON](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=6505032&eventNumber=0) @ Grangemoor
- Additionally, I have added the start of a test framework as I try to work out to prevent breaking issues like this in the future. The tests use Mocha, and are configured to run in Travis builds
- In addition to Mocha, we have code coverage metrics from the …
=> Fix event link error

browser-extensions/common/js/lib/challenges.js
Adds row at the top of the Tons of runs table to show progress towards the 100 badge (ie how many times highest parkrun run).
Tested on
- [someone with both badges](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=26084&eventNumber=0#double-ton) - shows two badge rows
- [someone without either badges](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=2363530&eventNumber=0) - shows additional row at the top of the table indicating which parkrun is currently highest and how many times run
- [someone with no runs](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=236353000&eventNumber=0#all-weather-runner) - blank rows for the two badges and no additional row showing progress (ie it doesn't blow up)
=> show progress when no ton badges awarded yet

.travis.yml, build/extension-chrome/build.sh, build/extension-firefox/build.sh
- Build was previously putting node dependencies and coverage data into the built zip files
=> Tidy up bundling process

browser-extensions/chrome/manifest.json, browser-extensions/firefox/manifest.json
- The Chrome extension webstore now asks for justification for each
permission, and I couldn't justify the activeTab permission because
I didn't know how we used it. Turned out, that we don't, and so I
removed it from both the Firefox and Chrome manifests
- https://developer.chrome.com/extensions/activeTab
=> Remove activeTab permission, which we don't need

website/_posts/2020-02-16-v1.1.1-name-badge-tons-netherlands.markdown
This will make the announcement less confusing
=> Rename v1.1.0 blog post to v1.1.1 to match the latest fix

.github/workflows/build-website.yml, build/website/copy-assets.sh
Travis CI is becoming increasingly slow and as of 2021-05-16 says:
> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.
It said this back in January too, which is when I first started looking into Github Actions, but life got in the way.
So, lets move over what I achieved over in my testing repo, and see if we can gradually get this repo to build everything with Actions.
I'm going to disable Travis, and  merge this to the master branch to get the ball rolling. We need to have something in the main branch for it to do anything, and having it half-broken will force me to fix it
=> Switch from Travis CI to Github Actions

browser-extensions/common/js/content-scripts/content-script-athleteeventresultshistory.js
Resolves #277 for non org.uk sites - uses local parkrun site for volunteer data and (as we're now looking at non-English language sites) selects volunteer table using id attribute rather than 'Volunteer summary'.
I don't think any further changes to policies are required to make this work.
=> Handle volunteer data on non org.uk sites 

.github/workflows/build-extension.yml
Something in the Github Actions build is complaining about not supporting node 10, so I'm going to try going up to 12.
It happens when we try and run the `web-ext` command to build the extension.
```
Error: yargs supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs#supported-nodejs-versions
at Object.<anonymous> (/opt/hostedtoolcache/node/10.24.1/x64/lib/node_modules/web-ext/node_modules/addons-linter/node_modules/yargs/build/index.cjs:1:55294)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load …
```
=> Update github action build script to use node-12

browser-extensions/common/js/content-scripts/content-script-parkrunner.js, browser-extensions/common/js/lib/i18n.js
1. DE, AT - updates the translation for `table_all_results` in `i18n.js`
2. PL, DK, SE, FR, RU, JP, NL - alters the table caption comparison in `get_table()` to ignore the additional `-` character. 
3. Adds 'www' prefix to parkrun.co.nl and parkrun co.at in `i18n.js` to ensure they match the domain.
Resolves issues raised in #301
=> Update to site translation handling including table captions

.github/workflows/build-website.yml
- By having a scheduled build we appear to be at risk of the workflow being disabled (if there are no new commits), and that means it doesn't run for any reason, even PRs that come along later, so lets just turn it off
=> Remove scheduled website build

browser-extensions/common/js/content-scripts/content-script-parkrunner.js
- For https://github.com/fraz3alpha/running-challenges/issues/355
- Sort the completed events chronologically
- We need to check that the dates aren't weirdly different on the US pages, or in the US locale, that breaks this
=> Order processed parkruns before returning

browser-extensions/common/js/content-scripts/content-script-parkrunner.js, browser-extensions/common/js/lib/challenges_ui.js
When you toggle a challenge's visibility, it will now persist it, meaning that it will stay like that for each page you visit.
Much of this came from a previous PR which included other things, so this bring it in on its own: https://github.com/fraz3alpha/running-challenges/pull/203
=> Persist hiding challenges

.github/workflows/build-extension.yml, .github/workflows/build-staging-website.yml, .github/workflows/build-website.yml, .github/workflows/release-test.yml, Dockerfile, browser-extensions/common/js/tests/package-lock.json
- Updates Github Actions steps that were using node 12 to node 16, as per https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- Updates our internal scripting that uses node to use 16 as well
- Huge change to the contents of the `package-lock.json` file, as basically everything has changed.
Also needed to fix the token used to push to the staging site to get that GH build working again
=> Switch from node 12 to 16

browser-extensions/common/js/lib/challenges.js
Just removing everything between parentheses and trimming the whitespace, fixes it and doesn't look to cause any other issues.
=> Fixed bug with AthleteID being shown in "Name Badge" challenge.

website/_config.yml, website/_includes/google-analytics-staging.html, website/_includes/google-analytics.html
This doesn't work on staging, as it should, because it doesn't override the `_includes/head.html` file for some reason, I keep getting the default, but the updated values should mean the data is sent to the right place for GA4
=> Switch to Google Analytics 4

browser-extensions/chrome/manifest.json, browser-extensions/common/js/tests/ui-test/package-lock.json, browser-extensions/common/js/tests/ui-test/package.json, browser-extensions/common/js/tests/ui-test/supporting-data/etc-hosts.txt, browser-extensions/firefox/manifest.json
- Remove options that were causing (non-terminal) plugin load errors on Firefox
- Fix image loading permission problems for images referenced in CSS files
- Remove duplicate include line for `cache.js`
=> Extra fixes for manifest v3

browser-extensions/common/js/lib/challenges_ui.js
parkrun names weren't appearing, that's because of the switch to the new tag creation mechanism
=> Fix text elements in SVG
