fraz3alpha/running-challenges

browser-extensions/chrome/js/background.js

- For #16 
- the https page is currently badly rendered, so don't link to it

Make the icon link to a http, not https page

---

browser-extensions/chrome/js/content-scripts/content-script-athleteeventhistory.js
browser-extensions/chrome/manifest.json

Add link onto parkrun event results page

---

browser-extensions/chrome/js/background.js

Increase geo.xml cache timeout to 3 days

---

browser-extensions/chrome/js/content-scripts/content-script-athleteeventresultshistory.js
browser-extensions/chrome/js/lib/challenges.js
browser-extensions/chrome/js/lib/challenges_ui.js

- For #11 
- Refactor the construction of the challenges data to enable 
optional passing of help text
- Add help text to the challenges data

Support, and add, help hover text

---

browser-extensions/chrome/html/help.html

- Forgot to update the help for #18

Update help with list of parkrun sites it works on

---

browser-extensions/chrome/html/options.html
browser-extensions/chrome/js/background.js
browser-extensions/chrome/js/options.js

- For #29 
- Adds a drop-down selection for your home parkrun
- Routes the link through to the local parkrun site when set, else defaults to the .org.uk site

Add home parkrun selection

---

browser-extensions/chrome/js/background.js
browser-extensions/chrome/js/translations.js
browser-extensions/chrome/manifest.json

- Tidy things up for the public

Bump version to v0.3.0.9 and remove lots of debug messages

---

browser-extensions/chrome/js/lib/challenges.js

Fix stats for parkruns with no location

---

browser-extensions/chrome/js/content-scripts/content-script-athleteeventresultshistory.js
browser-extensions/chrome/js/lib/challenges.js

- For #66 
- Add back in the partial completion badge functionality (for the quarter-cowell etc..)
- Add back in the obsessive badges

Fix missing obsessive and fractional cowell badges

---

browser-extensions/chrome/js/content-scripts/content-script-athleteeventresultshistory.js
browser-extensions/chrome/js/lib/challenges.js

- Needed to mark that the volunteer data was available, and also
add help text to the two stats that were being calculated

Add the volunteer stats back in

---

browser-extensions/chrome/js/lib/challenges_ui.js

- People keep asking what each stat means, this adds a line to point them in the 
direction of the hover text that is already there

Add line to indicate how to get more information on the stats

---

browser-extensions/chrome/js/lib/challenges.js
browser-extensions/chrome/js/lib/challenges_ui.js
browser-extensions/chrome/js/lib/third-party/leaflet-canvasicon/leaflet-canvasicon-0.1.4.js
browser-extensions/chrome/js/lib/third-party/leaflet-piechart/leaflet-piechart-0.1.2.js
browser-extensions/chrome/manifest.json

Basic navigable map for regionnaire

---

browser-extensions/chrome/js/lib/challenges.js

- A few small fixes to the help text in some of the stats

Small fixes

---

website/_pages/faq.md

Add a FAQ section for why we can't have a grace period for Regionnaire

---

browser-extensions/common/html/testing.html
browser-extensions/common/js/background.js
browser-extensions/common/js/content-scripts/content-script-athleteeventresultshistory.js
browser-extensions/common/js/lib/challenges.js
browser-extensions/common/js/testing.js

- We should tell the user if we've been able to fetch all of the required data for stats and challenges, and the recommendation of how to fix it (refresh, mostly)
- For #77

Add extra debug in for incomplete fetching of dependencies

---

browser-extensions/common/js/content-scripts/content-script-athleteeventresultshistory.js

- They got lost again, so here I am adding them back in

Re-adding the volunteer stats, again

---

browser-extensions/common/js/lib/challenges.js

- Use the algorithm provided by @JazzyJ87 in #90

Use working code this time for the tourism streak

---

website/_pages/map.md
website/assets/css/leaflet-slidemenu/leaflet-sidemenu.css
website/assets/js/lib/leaflet-slidemenu/leaflet-sidemenu.js
website/assets/js/lib/map.js

- Improve the dropdown box ordering
- Add parkrun / junior parkrun differences
- Add padding to the contents
- Add links to other people's maps

Improve website map

---

website/_config.yml
website/_includes/google-analytics-staging.html
website/_includes/google-analytics.html
website/_includes/head.html
website/assets/js/lib/leaflet-slidemenu/leaflet-sidemenu.js
website/assets/js/lib/map.js

- Adds a different Google Analytics token for staging
- Have a go with Google Analytics and see if people are using the map

Add Google Analytics to staging website & map interactions

---

browser-extensions/chrome/manifest.json
browser-extensions/firefox/manifest.json

- For #154 
- Adds the .my domain to the manifest.json files for both firefox and chrome browsers.

Add Malaysia URLs so that the challenges can display on .my domain.

---

browser-extensions/chrome/manifest.json
browser-extensions/firefox/manifest.json

- In case we want to fetch anything from our website, add it to the list of allowed locations in the content security policy

Add running-challenges.co.uk to the list of allowed sites

---

README.md
website/_posts/2019-04-04-v0.7.5-released.markdown

- Publish blog post for v0.7.5
- Document tasks for doing a release so we don't forget the steps

Post release tasks

---

browser-extensions/common/js/lib/challenges.js

Add Pont y Bala parkrun to the Full Ponty Challenge

---

website/_posts/2019-05-19-alphabeteer-panic-what-happened-to-zary.markdown

Add Alphabeteer blogpost

---

browser-extensions/common/js/lib/i18n.js

`table_all_results` value updated in Polish (previously translated differently) and added in Russian (previously in English?).
For #182

update All Results string in Polish and Russian.

---

browser-extensions/common/js/lib/i18n.js

Add missing Event Day Course Check Italian translation

---

website/_posts/2019-11-19-the-demise-of-geo-xml.markdown

Add blog post for geo xml changes

---

browser-extensions/common/js/lib/i18n.js

- Provided by Bill Steffancin ([A4782624](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=4782624&eventNumber=0)) via email
- For #212

Add first pass of Japanese translations

---

browser-extensions/common/js/lib/challenges.js

- Combines single-ton and double-ton challenges into a single challenge with badges at 100 and 200 milestones
- #237 
- manually tested with:
- [single-ton only achieved](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=1309364&eventNumber=0#double-ton)
- [double-ton only achieved](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=930349&eventNumber=0#double-ton)
- [single-ton and double-ton achieved at separate locations](https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=26084&eventNumber=0#double-ton)
- no ton achieved at all

Combine single-ton and double-ton into single table

---

browser-extensions/common/js/background.js
browser-extensions/common/js/lib/challenges_ui.js

- Try to not parse the wiki page if the contents are malformed.
- Make some tweaks to the active parkruns in the explorer map

Make technical info parse more robust

---

browser-extensions/common/js/lib/challenges.js

- The `is_our_page()` function just didn't work at all - I'm ashamed I didn't pick up on this!
Still, that's why we are adding tests, and we'll get to complete coverage eventually!
- This makes the function work, and work like the old individual calls did. It also makes it 
not fall in a heap when the tests are run

Fix nendy again

---

browser-extensions/common/js/content-scripts/content-script-athleteeventresultshistory.js
browser-extensions/common/js/lib/challenges.js
build/version.sh

- Based on PR #262 by @rboyatt 
- Also corrects value in the header at the top of the page
- Timeout of 10 days (1st March 2020)

Fixing error 482

---

website/_pages/about.md
website/_pages/faq.md
website/_pages/privacy.md

Pull out the privacy statement onto its own page so that we can link to it as necessary

add privacy page and links to it

---

.github/workflows/build-extension.yml
browser-extensions/common/js/content-scripts/content-script-parkrunner.js
browser-extensions/common/js/lib/i18n.js
browser-extensions/common/js/test-selenium/selenium-docker.js

- To help with https://github.com/fraz3alpha/running-challenges/issues/301, run the tests against more countries
- If this throws up any issues (spoiler, it did), we will fix them here before considering this for merging into the master branch

Run selenium tests against all countries

---

.github/workflows/release-test.yml

- Provide a way to test our latest build against the current parkrun websites, which will tell is whether it still works

Initial version of release test workflow

---

website/_posts/2022-05-15-whats-broken-now-may-2022-edition.markdown

- Stupidly had the year as 2021 on the blog post, so corrected it to 2022

correct oops, wrong date

---

browser-extensions/common/js/lib/challenges.js
browser-extensions/common/js/test/test_challenges.js

Trying to make sure that the tests pass after they failed from @JazzyJ87 's initial [PR](https://github.com/fraz3alpha/running-challenges/pull/325)

Jazzy j87 add name badge map

---

.github/workflows/build-staging-website.yml

I need to merge the first version of this, otherwise I can't run the action

Add staging website build

---

.github/workflows/build-staging-website.yml

The intent of this PR will be to:
- Build each new branch into it's own directory
- Host those websites on the staging domain
- Clean up old branches

Actually get the staging website working

---

browser-extensions/common/js/lib/challenges_ui.js

- Fixes https://github.com/fraz3alpha/running-challenges/security/code-scanning/1
- Fixes https://github.com/fraz3alpha/running-challenges/security/code-scanning/2
- Does what the security scanning tool suggests

add noopener noreferrer to a href _blank links

---

browser-extensions/chrome/manifest.json
browser-extensions/common/html/options.html
browser-extensions/common/html/testing.html
browser-extensions/common/js/test/test_challenges.js
browser-extensions/firefox/manifest.json
js/lib/third-party/jquery/README.md
js/lib/third-party/jquery/jquery-3.6.0.js

Our version of JQuery was 4 years old, it could do with an update

Upgrade JQuery 3.3.1 > 3.6.0

---

.github/workflows/build-staging-website.yml

- Fix the lack of updating of index.html

Display all staging builds

---

browser-extensions/common/js/lib/challenges.js

Help text needs to be updated now we've switched from using home parkrun as the centre.

Update help text for average parkrun location

---

.github/workflows/build-staging-website.yml

Attempts to make the staging website build more reliable and not crash the Jekyll builder

Try some jekyll fixes

---

browser-extensions/common/js/lib/challenges.js

Pulling this in, having missed it out

Update help text for average parkrun location. (#347)

---

browser-extensions/common/js/content-scripts/content-script-athleteeventhistory.js
browser-extensions/common/js/content-scripts/content-script-athleteresultshistory.js
browser-extensions/common/js/content-scripts/content-script-parkrunner-summary.js
browser-extensions/common/js/content-scripts/content-script-parkrunner.js
browser-extensions/common/js/lib/challenges.js
browser-extensions/common/js/lib/challenges_ui.js

- For https://github.com/fraz3alpha/running-challenges/issues/351
- Replace 21 occurrences of `browser.getURL()` with `runtime.getURL()`

Replace extension.getURL with runtime.getURL

---

.github/workflows/build-staging-website.yml

Replace use of `github.ref_name` with something that doesn't have slashes

replace slashes with underscores in branch name

---

browser-extensions/common/js/content-scripts/content-script-parkrunner.js
browser-extensions/common/js/testing.js

- For https://github.com/fraz3alpha/running-challenges/issues/385

found a few more references to the technical event info to remove

---

website/_posts/2023-06-28-v1.4.0-fixes-and-wiki-gone-away.markdown

- I missed a few thanks in the blog post for v1.4.0 last night, adding them in

Add extra thanks for 1.4.0

---

.github/workflows/build-extension.yml

The build for #403 failed [unrelated to the changes therein](https://github.com/fraz3alpha/running-challenges/actions/runs/10759796752/job/29836955578#step:7:25).
- **Use the newer `compose` plugin**
- **Use script-apt `apt` commands**
Check build output.
It has been a while since this repository has been updated. I'm keen to help keep it maintained.

Fix UI Tests
